/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/8.0.1/samples
 */

plugins {
    `java-library`
}

// The root project doesn't produce a JAR.
tasks["jar"].enabled = false

// SUBPROJECT SETTINGS
subprojects {
    val subproject = this

    apply(plugin = "java-library")

    repositories {
        mavenLocal()
        mavenCentral()
    }
}
