/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/8.0.1/userguide/multi_project_builds.html
 */

rootProject.name = "directed-codegen"

// example code gen plugin
include(":codegen")

// Include all example integrations
include(":integrations:change-type-for-trait")
include(":integrations:add-method-for-trait")

// Test Package
include(":codegen-test:example-model")
include(":codegen-test:base")
include(":codegen-test:add-method-for-trait")
include(":codegen-test:change-type-for-trait")


pluginManagement {
    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
    }
}
